[package]
name = "pkl-rust-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
rand = "0.8.5"
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde = { version = "1.0.197", features = ["derive"] }
url = "2.5.0"
